live_config_reload: true

scrolling:
    history: 10000
    multiplier: 10

selection:
    semantic_escape_chars: '|:"'' {}()[]<>'
    save_to_clipboard: true

window:
  padding:
    x: 0
    y: 0
  decorations: none

font:
  normal:
    family: "OperatorMono Nerd Font"
    style: Book
  bold:
    family: "OperatorMono Nerd Font"
    style: Bold
  italic:
    family: "OperatorMono Nerd Font"
    style: Italic
  bold_italic:
    family: "OperatorMono Nerd Font"
    style: Bold Italic
  size: 20.0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

# base16-eighties
# colors:
#   primary:
#      background: "#2D2D2D"
#      foreground: "#D3D0C8"
#   normal:
#      black: "#2d2d2d"
#      red: "#f2777a"
#      green: "#99cc99"
#      yellow: "#ffcc66"
#      blue: "#6699cc"
#      magenta: "#cc99cc"
#      cyan: "#66cccc"
#      white: "#D3D0C8"
#   bright:
#      black: "#747369"
#      red: "#f2777a"
#      green: "#99cc99"
#      yellow: "#ffcc66"
#      blue: "#6699cc"
#      magenta: "#cc99cc"
#      cyan: "#66cccc"
#      white: "#F2F0EC"
#
# Nord Theme
colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'

background_opacity: 0.9

cursor:
  style: Block
  unfocused_hollow: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: N,      mods: Command,         action: SpawnNewInstance }
  - { key: Q,      mods: Command,         action: Quit             }
  - { key: W,      mods: Command,         action: Quit             }
  - { key: F,      mods: Command|Control, action: ToggleFullscreen }
